### ISSUE TITLE
Migrate from CRA to Vite

### ISSUE THREAD

**Issue by hironytic** [hironytic/MobConfVideoWeb#230]
Migrate from "Create React App" to Vite because CRA doesn't seem to be maintained.

This article could help.
https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

**Comment by GIT-Gizmo** [comment]
I have forked the repo and will try to help in migrating if you don't mind

**Comment by GIT-Gizmo** [comment]
I have migrated to vite but looks like I'm having issues modifying your env to make it all work

**Comment by hironytic** [comment]
With my understanding, Vite can access only environment variables prefixed with `VITE_`. So we need rename `REACT_APP_FIREBASE_CONFIG` with `VITE_FIREBASE_CONFIG`.

Is that you are referring to?

**Comment by GIT-Gizmo** [comment]
Oh, true. I'll fix that

**Comment by GIT-Gizmo** [comment]
Ok, I've done that and I noticed your .env.local is in gitignore for understandable reasons and I think all that's left is for you to set your VITE_FIREBASE_CONFIG to a valid json string. Should I commit and PR now?

**Comment by GIT-Gizmo** [comment]
Yes I think all that's left to make it work. Should I commit and PR now? You can create a new branch to test it first before pushing to the main branch
